apiVersion: v1
kind: Service
metadata:  
  name: {{ .Values.cust1.serviceName }}
spec:
  selector:    
    app: {{ .Values.cust1.appName }}
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 80
    nodePort: {{ .Values.cust1.serviceNodePort }}
    protocol: TCP