apiVersion: v1
kind: Service
metadata:  
  name: {{ .Values.cust2.serviceName }}
spec:
  selector:    
    app: {{ .Values.cust2.appName }}
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 80
    nodePort: {{ .Values.cust2.serviceNodePort }}
    protocol: TCP